### ISSUE TITLE
Token not refreshing after 1 hour

### ISSUE THREAD

**Issue by mchint01** [manishrasrani/ms-adal-angular6#2]
Login is working as expected, but JWT we are receiving is expiring after 1 hour. And after that, if we try to call an API/refresh page, user is being logged-out.

Is there anything we need to config specifically?

Our config section:

 adalConfig: {
    tenant: 'XXXXX.onmicrosoft.com',
    clientId: 'XXXXXXX-ec4f-429b-9aa3-XXXXXXXXXX',
    endpoints: {
      'https://graph.microsoft.com': '00000003-0000-0000-c000-000000000000'
    },
    postLogoutRedirectUri: 'XXXXXXXXXXX',
    cacheLocation: 'localStorage',
    popUp: false
  },

**Comment by saransh944** [comment]
use should use adalService.acquireToken method for renewing the token.

**Comment by Fallenstedt** [comment]
@mchint01 Your access token should be configurable. You can configure it to expire after 1 day. 

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#configurable-token-lifetime-properties

**Comment by jrmcdona** [comment]
Are you supposed to check if your token expired or will the library automatically take care of renewal?

**Comment by saranshahlawat** [comment]
@jrmcdona , the library automatically takes care of it. You need to use 'acquireToken' method which will generate a new token in case the token is expired and save it in the session storage. Once you have a valid token in the session storage, next time you call 'acquireToken' it will fetch that token from session storage and use it. Otherwise, it will generate a new token and save it in the session storage.
Just remember to call 'acquireToken' after logging in to your application and that method will take care of everything for you. 
Also, as a side note, you might want to put an error condition that if 'acquireToken' method fails to fetch the token, you should logout the user and take them to login page.

**Comment by manishrasrani** [comment]
@saranshahlawat you are right, thanks for the clarification.
